### PR TITLE
Improving the cards design 

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved the issue #21 
made it like:
portf2
portfolio89

### CODE REVIEW

**Review by soumali28 — CHANGES_REQUESTED** [review]
Instead of the white background for the card can you use different color or use glassmorphism.

**Comment by zugzwang03** [comment]
ok
Is it fine now?

**Review by soumali28 — APPROVED** [review]

**Comment by Programming-School-Pro-Coding** [comment]
Let's Merge

**Comment by zugzwang03** [comment]
Yeah I will be resolving the dark mode implementation issue #23  in a separate PR. You can merge and close this PR @soumali28 .

**Pull request merged**
