### PR TITLE
styled toggle button and align it with title

### PR DESCRIPTION
**Pull request by mridulpal019**
Screenshot (86)
Screenshot (87)

### CODE REVIEW

**Review by soumali28 — CHANGES_REQUESTED** [review]
Screenshot 2022-08-15 195840
- can you align them evenly just space it out a bit more for both the themes

**Comment by soumali28** [comment]
@mridulpal019  any updates??

**Comment by mridulpal019** [comment]
hi ! sorry for the delay i will do the said changes today itself

**Comment by mridulpal019** [comment]
Screenshot (94)
Screenshot (96)
@soumali28 Kindly check the changes and let know if its ok or not..

**Comment by Susmita-Dey** [comment]
@mridulpal019 Your branch has merge conflicts. Kindly fix it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Review by soumali28 — CHANGES_REQUESTED** [review]
resolve the conflicts

**Comment by mridulpal019** [comment]
@soumali28 @Susmita-Dey resolved the conflicts

**Comment by mridulpal019** [comment]
@soumali28 @Susmita-Dey resolved the conflicts

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by mridulpal019** [comment]
#34

**Pull request merged**
