### PR TITLE
parkhi website

### PR DESCRIPTION
**Pull request by PARKHI277**
This is my portfolio. I would like to add this in your project . Kindly review it.

### CODE REVIEW

**Comment by soumali28** [comment]
Hey did you open a issue? Also are you a SSOC participant?

**Comment by PARKHI277** [comment]
> Hey did you open a issue? Also are you a SSOC participant?

Yes, I am a SSOC participant and also choose your project for the same.

**Comment by soumali28** [comment]
Ok but I think you haven't created an issue just create a new issue saying u want to add your porfolio and I'll assign you then add the issue number in this Pr.

**Comment by PARKHI277** [comment]
> Ok but I think you haven't created an issue just create a new issue saying u want to add your porfolio and I'll assign you then add the issue number in this Pr.

done.

**Pull request closed without merging**
