### PR TITLE
Create Mohamed.json

### PR DESCRIPTION
**Pull request by Programming-School-Pro-Coding**

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Can you add your photo?

P.S. It would be used in the future in the landing page of this repo.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Reusable

**Comment by Programming-School-Pro-Coding** [comment]
> Can you add your photo?
> 
> .S. It would be used in the future in the landing page of this repo.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question  |  **Tags:** Reusable

I will add my logo not my photo

**Comment by Programming-School-Pro-Coding** [comment]
Do you mean photo for the landing page ?

**Comment by Susmita-Dey** [comment]
@Programming-School-Pro-Coding  Okay, you can add that.

**Comment by Programming-School-Pro-Coding** [comment]
Success

**Comment by Programming-School-Pro-Coding** [comment]
Hey @Susmita-Dey

**Comment by Programming-School-Pro-Coding** [comment]
Please finish the review

**Comment by Susmita-Dey** [comment]
> Please finish the review

Kindly check the instructions once and add the image

**Review by Susmita-Dey — APPROVED** [review]
LGTM! Thanks for contributing. Merging it to main. 😊

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Pull request merged**
