### PR TITLE
Add profile

### PR DESCRIPTION
**Pull request by vedantpople4**

### CODE REVIEW

**Comment by Programming-School-Pro-Coding** [comment]
@vedantpople4 Why you change the name of the file from label.yml to labeler.yml ?

**Comment by vedantpople4** [comment]
> @vedantpople4 Why you change the name of the file from label.yml to labeler.yml ?

I was getting error I the actions check. Found this relative solution :
https://github.com/actions/labeler/issues/16

**Review by Programming-School-Pro-Coding — CHANGES_REQUESTED** [review]
Undo the file rename

**Review by Programming-School-Pro-Coding — APPROVED** [review]
LGTM

@Susmita-Dey Please add your review now

**Comment by vedantpople4** [comment]
Thanks, so does it always give error ?

**Comment by Programming-School-Pro-Coding** [comment]
@vedantpople4 Please wait while @Susmita-Dey give you her review

**Comment by Programming-School-Pro-Coding** [comment]
> Thanks, so does it always give error ?

Yes, See the closed pull requests

**Comment by Programming-School-Pro-Coding** [comment]
Hey @vedantpople4 

If you want to a readme file for your github profile or you have one please add your own changes here: https://github.com/Programming-School-Pro-Coding/Programming-School-Pro-Coding and then create a pull request for the changes

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for contributing.



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient, Maintainable

**Pull request merged**
