### PR TITLE
saikat roy portfolio link and git repo added

### PR DESCRIPTION
**Pull request by njmsaikat**

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Can you add your photo?

P.S. It would be used in the future on the landing page of this repo.


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by njmsaikat** [comment]
In which directory. There wasn't any instructions for photo.

**Comment by Susmita-Dey** [comment]
> In which directory. There wasn't any instructions for photo.

Kindly check the instructions once and add the image

**Comment by njmsaikat** [comment]
yah image added now

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for contributing.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Pull request merged**
